name: Smoke E2E – Job Application Flow (Chrome)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run:
    runs-on: ubuntu-latest
    name: Smoke E2E – Job Application Flow (Chrome)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: .
